data_dir: dataset

data_name: 'income' # iris, wine, boston, mnist, income
scalar: standard

epochs: 100
batch_size: 128
test_batch_size: 10000

model_name: TCN # TCN, MLP

# choise in noise, shuffle, flip, random_flip, add_dim, random_collapse, random_resize
# you must splits by ",", not space.
augment:
  random_flip: 0.5 # p
  noise: 1. # esp
  random_collapse: 0.2 # p
  shuffle: 0.3 # p
  random_resize: 0.2 # p

augmenters: [random_flip,
             noise, 
             random_collapse, 
             shuffle, 
             random_resize
             ]

early_stopping_patience: 10

seed: 42

defaults:
  - override hydra/sweeper: ax
hydra:
  run:
    dir: outputs/single/${hydra.job.name}/${data_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: outputs/multirun/${hydra.job.name}/${data_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  sweeper:
    ax_config:
      max_trials: 1000  # 最大試行回数
      early_stop:
        minimize: false
        max_epochs_without_improvement: 100
      experiment:
        minimize: false  # 最適化の方向

      # 最適化対象のハイパーパラメータ
      params:
        batch_size:
          type: choice
          values: [8,16,32,64,128]