data_dir: dataset

data_name: mnist # iris, wine, boston, mnist, income, blog, covertype
scalar: standard

epochs: 1000
batch_size: 128
test_batch_size: 10000
self_epochs: 10

labeled_rate: 0.1
beta: 1

opt: SGD # SGD, Adam
self_opt: RMSprop # RMSprop, Adam

model_name: MLP # TCN, MLP

# augment posision
# choise: [input, model]
augment_pos: model

augment:
  random_flip:
    p: 0.5
  noise:
    eps: 0.1
  random_collapse:
    p: 0.2
  shuffle:
    p: 0.4
  random_resize:
    p: 0.3
  random_erasing: 
    p: 0.5
    erasing_rate: 0.3

augmenters: [
             random_flip,
             noise,
             random_collapse,
            #  shuffle,
             random_resize,
             random_erasing,
             ]

method: fixmatch
semi_para:
  normal:
    k: 5
  fixmatch:
    strong:
        random_flip:
          p: 0.5
        noise:
          eps: 1.
        random_collapse:
          p: 0.5
        shuffle:
          p: 0.5
        random_resize:
          p: 0.5
        random_erasing:
          p: 0.5
          erasing_rate: 0.5

early_stopping_patience: 50

seed: 42

# defaults:
#   - override hydra/sweeper: ax
hydra:
  run:
    dir: outputs/single/${hydra.job.name}/semi/${data_name}/${augment_pos}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: outputs/multirun/${hydra.job.name}/semi/${data_name}/${augment_pos}/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  # sweeper:
  #   ax_config:
  #     max_trials: 1000  # 最大試行回数
  #     early_stop:
  #       minimize: false
  #       max_epochs_without_improvement: 100
  #     experiment:
  #       minimize: false  # 最適化の方向

  #     # 最適化対象のハイパーパラメータ

        
        